### ISSUE TITLE
M-W ambiguity

### ISSUE THREAD

**Issue by thewchan** [weijia-cheng/emma-goldman_my-disillusionment-in-russia#10]
These are probably okay but considered _less common_ by M-W:
`antisemitism` <-> `anti-semitism`
`holdup-men` <-> `holdup men`

**Comment by weijia-cheng** [comment]
I think these are OK. "Holdup men" appears to be in the abridged dictionary. "Antisemitism" is a change initiated by modernize-spelling and I think it's preferable in modern style guides ([AP](https://twitter.com/APStylebook/status/1385687075635204100) and [NYT](https://jewishinsider.com/2021/12/ny-times-replaces-anti-semitism-with-antisemitism-in-updated-style-guidance/)).
