### ISSUE TITLE
Missing <abbr>?

### ISSUE THREAD

**Issue by thewchan** [weijia-cheng/emma-goldman_my-disillusionment-in-russia#11]
`chapter-21.xhtml` line 20:
I found the latter in charge of a cultivated and charming man, <abbr>Dr.</abbr> N⁠⸺. For twenty years he had been head of the hospital and he took interest as well as pride in showing us about his institution and relating its history.

Dr. `N` <- Might need something here? Unsure

**Comment by weijia-cheng** [comment]
I believe this is a [partially obscured word](https://standardebooks.org/manual/1.6.2/8-typography#8.7.7.8.4) and doesn't need any `<abbr>` semantics.
