### ISSUE TITLE
hotel/hôtel

### ISSUE THREAD

**Issue by thewchan** [weijia-cheng/emma-goldman_my-disillusionment-in-russia#2]
`find-mismatched-diacritics` reports the following for hotel/hôtel:

`chapter-3.xhtml` line 31:
...There I was graciously received by his wife and invited to dinner served by their maid. After that Radek began the difficult task of getting me quartered in the **Hotel** National, known as the First House of the Moscow Soviet....

`chapter-4.xhtml` line 20:
The National, like the Petrograd Astoria, was a former **hotel** but not nearly in as good condition. No rations were given out there except three quarters of a pound of bread every two days. Instead there was a common dining room where dinners and suppers were served...

`chapter-6.xhtml` line 22:
However, the renovation of the houses that were to serve as living quarters for the exiles was not accomplished so easily. I inspected what, as I was told, had once been first-class **hotels**...

line 26:
...But, then, few people in Russia know how to work. The situation looked hopeless. Only ten days remained till the arrival of the deportees, and the “**hotels**” assigned for their use were still in as uninhabitable a condition as before...

line 27:
...The prepared **hotels** were locked and sealed; they were not to be used for the returned war prisoners because “they were prepared for American deportees who still might come.” All the efforts and labour had been in vain.

`chapter-7.xhtml` line 15:
...I had learned from my previous experience with the **hotels** that much valuable time was lost because of the failure to provide for those actually employed on such work...

`chapter-23.xhtml` line 30:
...The last time I saw him was at the guest house, the **Hôtel** International, in Petrograd...

`chapter-24.xhtml` line 17: 
...Louise Bryant had fallen in a dead faint and was lying face downward on the damp earth. After considerable effort we got her to her feet. Hysterical, she was taken in the waiting auto to her **hotel** and put to bed. Outside, the sky was clothed in gray and was weeping upon the fresh grave of Jack Reed. And all of Russia seemed a fresh grave...

line 34:
...Arrived in Petrograd, I went to live temporarily in the **Hôtel** International. I intended to find a room somewhere else, determined to accept no privileges at the hands of the Government...

`chapter-29.xhtml` line 15:
The **Hôtel** de Luxe, renovated the previous year, became the foreign guest house of the Third International and was put in festive attire. The delegates began to arrive in Moscow.

line 26:
Some of the delegates had valiantly escaped to safety, unselfishly preferring the **Hôtel** de Luxe to Leavenworth Penitentiary, leaving their comrades behind in American prisons and their friends to refund the bonds they had heroically forfeited.

line 31:
In the face of abject want, with men, women, and children hungrily watching the white bread baked for the Luxe **Hotel** in its adjoining bakery, one of the American fraternal delegates wrote to a publication at home that...and on the Tverskaya and the Pushkin Boulevard, near the Luxe **Hotel**, street women mobbed the delegates with their attentions.

Most of these are probably false positives; but some proper nouns are inconsistent (e.g. Luxe Hotel vs. Hôtel de Luxe).

**Comment by weijia-cheng** [comment]
I think the only issue here is "Hôtel de Luxe" versus "Luxe Hotel." The word "hotel" outside of as part of a proper noun is always spelled the same way, and the other proper noun hotels are consistent. It is spelled as "Luxe Hotel" [in the text](https://archive.org/details/in.ernet.dli.2015.58226/page/n131/mode/2up?view=theater) but since it is clear from context that this is the same thing as the "Hôtel de Luxe," it does make sense to have them spelled the same way.
