### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by thewchan** [weijia-cheng/emma-goldman_my-disillusionment-in-russia#4]
`chapter-23.xhtml` line 29
By the time we reached the district where Makhno **h ad** been operating in September, he was cut off from us.

`h ad` -> `had`

**Comment by thewchan** [comment]
`chapter-24.xhtml` line 31
...**The’** Revolution had its roots deep down in the life of the people. The Communist State was based on a scheme forcibly applied by a political party.

`The’` -> `The`

**Comment by thewchan** [comment]
`chapter-26.xhtml` line 19
The other protest was made in reply to the plan of the Government to “liquidate” all private publishing establishments, including even those of the **coooperatives**, **The** protest was addressed to the Presidium of the All-Russian Congress of Soviets...

`coooperatives` -> `cooperatives`
`The` -> `the`

**Comment by weijia-cheng** [comment]
I think the first two have already been fixed, but the last one is a good catch.

**Comment by thewchan** [comment]
`chapter-24.xhtml` line 15
...But I was glad of what Kollontay had said. Not only because what she said **expresssed** Jack Reed better than anything else said that day, but also because it brought her nearer to me...

`expresssed` -> `expressed`

**Comment by thewchan** [comment]
`chapter-31.xhtml` line 17:
...Twenty-two years of living death in Schlüsselburg had failed to destroy her ardour. When the Citizens’ **Com mittee** was arrested...

`Com mittee` -> `Committee`

**Comment by thewchan** [comment]
`chatper-32.xhtml` line 29
...In the group there were also several students⁠—mere youths who had participated in the Anarchist hungerstrike in the Taganka prison.

`hungerstrike` -> `hunger strike`

**Comment by thewchan** [comment]
`chapter-33.xhtml` line 23
...The peasantry became the rock upon which the **bestlaid** plans and schemes of Lenin were wrecked....

`bestlaid` -> `best laid` or `best-laid`

**Comment by thewchan** [comment]
`chapter-33.xhtml` line 53:
Unlike the **physicial** proletarian, who can pick up his tools and tramp the world in search of a change from a galling situation...

`physicial` -> `physical` (??? Not sure about this one)

**Comment by thewchan** [comment]
`content.opf` line 46:

...Despite initial plans to fight the deportation order in court, Goldman eventually acquiesced in order to take part in thenew revolutionary Russia herself...

`thenew` -> `the new`

...Goldman concludes her account with a critique of the Bolshevik ideology in which she asserts that revolutionary change in instutitions cannot take place without corresponding changes in values...

`instutitions` -> `institutions`
