### ISSUE TITLE
Possible candidate to modernize

### ISSUE THREAD

**Issue by thewchan** [weijia-cheng/emma-goldman_my-disillusionment-in-russia#6]
`tcheka` -> `cheka`
`ikon` -> `icon`
`tchekists` -> `chekists`
`gayety` -> `gaiety`
`Tchicherin` -> `Chicherin`
~`un-revolutionary` -> `unrevolutionary`~

**Comment by weijia-cheng** [comment]
Unrevolutionary seems like an easy change. I'll ask about the others.
