### ISSUE TITLE
Possible words to check US/GB spelling

### ISSUE THREAD

**Issue by thewchan** [weijia-cheng/emma-goldman_my-disillusionment-in-russia#7]
`paralyzing` <-> `paralysing`
`pretenses` <-> `pretences`
`anesthetic` <-> `anaesthetic`
`defense` <-> `defence`
`somberness` <- `sombreness`

**Comment by weijia-cheng** [comment]
Oddly, this book doesn't seem consistent with the spelling of the same word in some cases. It is [paralyzing](https://archive.org/details/in.ernet.dli.2015.74435/page/n155/mode/2up) on one page and [paralysing](https://archive.org/details/in.ernet.dli.2015.74435/page/n89/mode/2up) on another page. "Pretense" vs. "pretence" and "defense" vs. "defence" seem to have the same issue. More to ask Alex about.
