### ISSUE TITLE
Check if location should be italicized? 

### ISSUE THREAD

**Issue by thewchan** [weijia-cheng/emma-goldman_my-disillusionment-in-russia#9]
`chpater-15.xtml` line 20
`On that occasion he had shown me about the trade union headquarters known as the <i xml:lang="ru-Latn">Dom Soyusov</i>, and explained how the organization worked...`

**Comment by weijia-cheng** [comment]
This looks like a similar situation to the other proper noun that's also a Russian phrase. I think "Dom Soyusov" literally means something like "Union House" or "House of Unions."
